version: '3.8'

services:
  bibliotecadb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/core:/var/lib/mysql
    networks:
      - bibliotecanet

  bibliotecaadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 9080:80
    networks:
      - bibliotecanet

  bibliotecamq:
    image: rabbitmq:3-management
    hostname: bibliotecamq
    volumes:
      - ./.docker/rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./.docker/rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./.docker/rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./.docker/rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - bibliotecanet
networks:
  bibliotecanet:
    driver: bridge
    ipam:
      driver: default
